### ISSUE TITLE
[Potential bug?] - Music player resets itself when placing a music disc into a jukebox

### ISSUE THREAD

**Issue by aking4125** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#11]
While the music player is playing, if you insert a music disc into a jukebox. It resets whatever is playing in the Music player (it still plays the disc from the jukebox normally). It also messes with the "Playing - [Music Disc]" text that appears on the screen as it quickly replaces it with whatever is playing in the Music player.

I'm assuming the music player and Jukebox is linked somehow?

**Comment by SokyranTheDragon** [comment]
There's only very small connection between the two, so I'm guessing it might be what's causing it. I'll go and check it out, and hopefully find the issue and fix it as well.

**Comment by SokyranTheDragon** [comment]
I couldn't reproduce it on my end. The 2 didn't interfere with each other at all on my end, and both were playing at the same time.

Maybe it's related to some other of your mods? I'm not really sure what the issue is.

**Comment by aking4125** [comment]
Hmm. So it seems. Let me check it out.

**Comment by SokyranTheDragon** [comment]
Due to lack of any activity or reports regarding this issue it's going to be closed.
