### ISSUE TITLE
Empty TE Pulverizer recipe

### ISSUE THREAD

**Issue by Krutoy242** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#17]
MIA added some broken recipes:

<img src="https://i.imgur.com/x9tn9s2.gif" width="200">

Also some more:

<img src="https://i.imgur.com/oWHoZgo.png" width="200">

[debug.log](https://www.dropbox.com/s/mm6icvocgyg5quz/debug.log?dl=0)

**Comment by Mrthomas20121** [comment]
how can you know these are added by MIA? pretty sure these aren't from MIA i had the same issue without mia installed.

**Comment by Krutoy242** [comment]
Seems like Im wrong then. Sorry for wrong case...
