### ISSUE TITLE
Crash with new Ice & Fire update

### ISSUE THREAD

**Issue by mistythecat** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#19]
[crash-2020-05-01_00.56.08-client.txt](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/4561936/crash-2020-05-01_00.56.08-client.txt)

**Comment by Codetoil** [comment]
Yeah that looks like the mod refactored or something. Will need an update to MIA.

**Comment by SokyranTheDragon** [comment]
Well, seems like I either did not get an email about this issue, or I haven't noticed it... Thankfully, I noticed a message over at CurseForge, which made me realize there was an issue.

Anyway, I've fixed it quite a while ago. If it still happens (or anything related to that Ice and Fire update), please open another issue.
