### ISSUE TITLE
Crash on initialization

### ISSUE THREAD

**Issue by twewy02** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#20]
[crash-2020-07-24_15.31.51-client.txt](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/4974140/crash-2020-07-24_15.31.51-client.txt)

**Comment by Lord-Zarnox** [comment]
[crash-2020-07-25_13.23.03-client.txt](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/4974855/crash-2020-07-25_13.23.03-client.txt)

**Comment by BugmanBugman** [comment]
yup, having this problem too

**Comment by Codetoil** [comment]
For some reason, MIA is attempting to register an enchantment without a registry name. Forge prevents this and crashes the game.

**Comment by Codetoil** [comment]
@SokyranTheDragon You should not attempt to register a null object. I have a feeling that that’s what causing the issue.

**Comment by Codetoil** [comment]
Well actually, forget that. It appears it was fixed in 1.12.2-0.1.8c

**Comment by Codetoil** [comment]
I would check to make sure the error is fixed tho.

**Comment by twewy02** [comment]
yes it appears this has been fixed in 0.1.8c
