### ISSUE TITLE
Crash with new FutureMC update 0.2.4.0

### ISSUE THREAD

**Issue by Landiie** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#22]
FutureMC just updated, so i put it into my modpack alongside your wonderful mod and it sadly crashed, something to do with honeyblocks i believe when i glanced at it! here is the crash report: [here](https://pastebin.com/EPwCRuSM) thank you so much for everything you do! <3

**Comment by SokyranTheDragon** [comment]
I'll look into it once I wake up, since it's pretty late right.

**Comment by SokyranTheDragon** [comment]
I did not have the crashing issue once I updated FutureMC in my dev environment, so I'm hoping that this was caused by some weird internal changed in FutureMC. I've uploaded a new version that should hopefully fix the issue (as I've built and tested it with the most recent FutureMC update). Could you check if it works?

**Comment by aking4125** [comment]
I had this problem earlier this morning then I stumbled upon this issue already being opened and dealt with. 

I updated FutureMC to 0.2.4.0 and updated MIA to 0.2.0c. 

All is good on my end. Everything is working perfectly fine in my private pack. Thank you for the quick response!

**Comment by SokyranTheDragon** [comment]
Good to hear that the issue has been fixed. @Landsurfer2000 is everything good on your end too?

**Comment by Landiie** [comment]
yes! It loads without fail and everything seems to be in working order! Thank you so much for the speedy fix Sokyran!! <3

**Comment by SokyranTheDragon** [comment]
Glad that it works! Enjoy playing the game!
