### ISSUE TITLE
Crash with recent Aether Legacy updates

### ISSUE THREAD

**Issue by SureinDragon** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#24]
Hi Sokyran!

Wanted to throw this mod into my kitchen sink modpack but I noticed it kept crashing, and I think it has something to do with the recent Aether update(s) that came over the last month. Just wanted to submit a crash report:

Here are my crash reports:

[With Thaumcraft](https://pastebin.com/0s3Mi5fT) - [With Chisel(?)](https://pastebin.com/sfNWAkj3) - [Additional Report](https://pastebin.com/pNGqT4bQ) for good measure.

Forge Version: 14.23.5.2847
The Aether Version: The Aether 1.12.2-v1.5.2
MIA Version: mia-1.12.2-0.2.0d

**Comment by SokyranTheDragon** [comment]
I'll get on this soon, thanks for reporting! I expected to have some issues with that update, but I haven't expected them to be so serious...

For now if you'll go into MIA settings and Aether category you'll be able to disable MIA additions/integrations for Aether, which should prevent those crashes (I'm 95% sure it should).

**Comment by SureinDragon** [comment]
No problem!

Actually, second two crash reports were before I disabled the entire Aether category, and the thaumcraft one popped up once everything was disabled. I'll give it a try with thaumcraft disabled and report back on it later today.

**Comment by SokyranTheDragon** [comment]
I've uploaded a new version that should fix the issue. It worked for me, so let me know if everything is alright on your end as well!

**Comment by SureinDragon** [comment]
Hey, I think that did the trick! I was able to launch with no issues. Thank you so much for the rapid response!
