### ISSUE TITLE
Issues with FutureMC and Quark compat in Stonecutter; odd recipes

### ISSUE THREAD

**Issue by Landiie** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#25]
thedarkcolour and i had some headscratching when the stonecutter started having odd quark recipes such as air equaling elder prismarine, and basalt missing textures in jei, we had no clue what was causing it, only to find out the source originates from MIA. I tried to remove futuremc quark compat in MIA's configs, only to have the same issue. Removing MIA completely remedies this issue however. I sadly wont be able to use MIA until this odd bug is somehow circumvented. Heres some screenshots!

![unknown](https://user-images.githubusercontent.com/43101146/95802170-95637500-0cb1-11eb-9dba-6b6724dd025c.png)

![unknown](https://user-images.githubusercontent.com/43101146/95802174-9d231980-0cb1-11eb-9a9e-5e5466d3ba60.png)

![](https://cdn.discordapp.com/attachments/765344797325525032/765365229001375804/unknown.png)

thanks for everything that you do, i hope this can be fixed soon D:

**Comment by Codetoil** [comment]
Looking into the error, it seems that the error is in `com.github.sokyranthedragon.mia.integrations.quark.FutureMcQuarkIntegration`

**Comment by Landiie** [comment]
can confirm what @Codetoil said, turns out i had to disable future mc integration with quark, AND quark integration with futuremc to stop this from happening, and it does originate from `com.github.sokyranthedragon.mia.integrations.quark.FutureMcQuarkIntegration`

**Comment by SokyranTheDragon** [comment]
Investigated it, removed a ton of broken recipes. Fixed in most recent version. Should be up soon.
