### ISSUE TITLE
[1.12.2] "MIA Encountered an Error" toast pops up on Menu screen but nothing seems broken

### ISSUE THREAD

**Issue by aking4125** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#27]
Hi,

I'm reporting the "MIA Encountered an Error" toast which pops up on the menu screen. Nothing in-game seems to be broken at least upon the first impression. 
![unknown](https://user-images.githubusercontent.com/11141831/107137839-4aafdd80-68de-11eb-9117-c356b7e586ec.png)

Clicking on the toast does nothing. So I'm sending my Logfile if anything. Both just incase.
[latest.log](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/5938339/latest.log)
[debug.log](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/5938340/debug.log)

No idea what exactly is the problem but, reporting it anyways. This is a private mod pack.

**Comment by SokyranTheDragon** [comment]
It looks like there's something up with adding Thaumcraft aspects to Extra Utilities stuff. This isn't a major issue, and I don't know why's that happening. This shouldn't cause any issues besides the blocks and items missing the aspects.
