### ISSUE TITLE
Crash with FutureMC

### ISSUE THREAD

**Issue by HassaFelipe** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#28]
Crash log link:
https://pastebin.com/Y2kVHBxi

I tried disable the bee feature on the future mc but it still no work, I don't know what do now.

**Comment by Codetoil** [comment]
I think you may need a newer version of FutureMC. 
https://www.curseforge.com/minecraft/mc-mods/future-mc/

**Comment by SokyranTheDragon** [comment]
This definitely looks like outdated version of FutureMC. There should be an update soon that'll make sure the even most recent version is supported.
