### ISSUE TITLE
Crashes on startup with latest FutureMC

### ISSUE THREAD

**Issue by freopt** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#32]
[crash-2022-03-29_20.26.34-client.txt](https://github.com/SokyranTheDragon/Minor-Integrations-and-Additions-MIA-/files/8375773/crash-2022-03-29_20.26.34-client.txt)

**Comment by RedRaspberry** [comment]
This issue is probably caused by the most recent FutureMC version (1.13) changing their recipes to use IIngredient rather than IItemstack

**Comment by SokyranTheDragon** [comment]
Oh yeah, change like that would definitely break stuff.

For now, I think changing the config files to disable FutureMC stuff should work, I think? Unless I made a mistake somewhere.

I'll try to look at all the current issues and fix the stuff that needs fixing over the next couple of days, hopefully.

**Comment by ACGaming** [comment]
Can confirm this, disabling the FutureMC integrations works just fine for now.

**Comment by aking4125** [comment]
Yeah Idk how to disable the FutureMC Integrations. There are many configs in the MIA folder and I disabled everything related to FutureMC and I'm still crashing.

**Comment by ACGaming** [comment]
> Yeah Idk how to disable the FutureMC Integrations. There are many configs in the MIA folder and I disabled everything related to FutureMC and I‘m still crashing.

Open `..\config\mia\future_mc.cfg` and set every option to `false`. Pretty straightforward.

**Comment by aking4125** [comment]
> > Yeah Idk how to disable the FutureMC Integrations. There are many configs in the MIA folder and I disabled everything related to FutureMC and I‘m still crashing.
> 
> Open `..\config\mia\future_mc.cfg` and set every option to `false`. Pretty straightforward.

Yeeeahhh.... Like I said, I did that. I set every single option related to FutureMC to False in ALL the configs. Even JUST the Future_mc.cfg. Still crashes with the exact same error as OP. However, just in-case I'll open a new issue, perhaps there is something different.

**Comment by SokyranTheDragon** [comment]
Should be fixed by ce8009e1b97f877c2cb9c332d2c3c598b25b7982, update should be released soon.
