### ISSUE TITLE
Crash when the game launch

### ISSUE THREAD

**Issue by QuerrixTU** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#7]
---- Minecraft Crash Report ----
// I blame way2muchnoise.

Time: 2020-01-26 12:53:43 CET
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minor Integration and Additions (mia)
Caused by: java.util.ConcurrentModificationException
    at java.util.HashMap$HashIterator.nextNode(Unknown Source)
    at java.util.HashMap$KeyIterator.next(Unknown Source)
    at java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
    at net.minecraft.world.storage.loot.LootTableManager.reloadLootTables(LootTableManager.java:47)
    at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35)
    at jeresources.util.LootTableHelper.getManager(LootTableHelper.java:177)
    at com.github.sokyranthedragon.mia.integrations.jer.JustEnoughResources.init(JustEnoughResources.java:124)
    at com.github.sokyranthedragon.mia.integrations.base.ModIntegrator.init(ModIntegrator.java:158)
    at com.github.sokyranthedragon.mia.proxy.CommonProxy.init(CommonProxy.java:65)
    at com.github.sokyranthedragon.mia.proxy.ClientProxy.init(ClientProxy.java:28)
    at com.github.sokyranthedragon.mia.Mia.init(Mia.java:70)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_241, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2927448576 bytes (2791 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -XX:+UseG1GC -Xmx4G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F6_pre1 101 mods loaded, 101 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                          | Version         | Source                                      | Signature                                |
       |:----- |:--------------------------- |:--------------- |:------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft                   | 1.12.2          | minecraft.jar                               | None                                     |
       | LCHI  | mcp                         | 9.42            | minecraft.jar                               | None                                     |
       | LCHI  | FML                         | 8.0.99.99       | forge-1.12.2-14.23.5.2847.jar               | None                                     |
       | LCHI  | forge                       | 14.23.5.2847    | forge-1.12.2-14.23.5.2847.jar               | None                                     |
       | LCHI  | itemphysic                  | 1.4.0           | minecraft.jar                               | None                                     |
       | LCHI  | smoothfontcore              | mc1.12.2-2.1.1  | minecraft.jar                               | None                                     |
       | LCHI  | randompatches               | 1.12.2-1.21.0.0 | randompatches-1.12.2-1.21.0.0.jar           | None                                     |
       | LCHI  | smoothfont                  | mc1.12.2-2.1.1  | SmoothFont-mc1.12.2-2.1.1.jar               | None                                     |
       | LCHI  | movillages                  | 1.5.4           | [1.12]MoVillages-1.5.4.jar                  | None                                     |
       | LCHI  | anvilfix                    | 1.0.3           | AnvilFix-1.12.2-1.0.3.jar                   | None                                     |
       | LCHI  | toughasnails                | 3.1.0.141       | ToughAsNails-1.12.2-3.1.0.141-universal.jar | None                                     |
       | LCHI  | applejuiceskin              | 1.0.0.4         | applejuiceskin-1.12.2-1.0.0.4.jar           | None                                     |
       | LCHI  | jei                         | 4.15.0.293      | jei_1.12.2-4.15.0.293.jar                   | None                                     |
       | LCHI  | appleskin                   | 1.0.9           | AppleSkin-mc1.12-1.0.9.jar                  | None                                     |
       | LCHI  | carrots                     | 1.0.0b1         | carrotslib-mc1.12.2-1.0.0b1.jar             | None                                     |
       | LCHI  | armorunder                  | 1.0.0           | armorunder-mc1.12.2-1.0.0.jar               | None                                     |
       | LCHI  | astikorcarts                | 1.12.2-0.1.2.7  | astikorcarts-1.12.2-0.1.2.7.jar             | None                                     |
       | LCHI  | quark                       | r1.6-177        | Quark-r1.6-177.jar                          | None                                     |
       | LCHI  | autoreglib                  | 1.3-32          | AutoRegLib-1.3-32.jar                       | None                                     |
       | LCHI  | baubles                     | 1.5.2           | Baubles-1.12-1.5.2.jar                      | None                                     |
       | LCHI  | bettercaves                 | 1.12.2          | bettercaves-1.12.2-1.6.0.jar                | None                                     |
       | LCHI  | forgelin                    | 1.8.4           | Forgelin-1.8.4.jar                          | None                                     |
       | LCHI  | betterfoliage               | 2.3.1           | BetterFoliage-MC1.12-2.3.1.jar              | None                                     |
       | LCHI  | betternether                | 0.1.8.6         | betternether-0.1.8.6.jar                    | None                                     |
       | LCHI  | blockdrops                  | 1.4.0           | blockdrops-1.12.2-1.4.0.jar                 | None                                     |
       | LCHI  | bottledmilk                 | 1.0.0           | BottledMilk-1.12-1.1.0.jar                  | None                                     |
       | LCHI  | brownmooshrooms             | 1.0.0           | brownmooshrooms-1.0.0.jar                   | None                                     |
       | LCHI  | carryon                     | 1.12.3          | CarryOn+MC1.12.2+v1.12.3.jar                | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
       | LCHI  | charm                       | 1.12.2-1.3.6    | Charm-1.12.2-1.3.6.jar                      | None                                     |
       | LCHI  | chunkpregenerator           | 2.1             | Chunk+Pregenerator+V1.12-2.2.jar            | None                                     |
       | LCHI  | colytra                     | 1.2.0.4         | colytra-1.12.2-1.2.0.4.jar                  | 2484ef4d131fdc0dca0647aa21b7b944ddb935a1 |
       | LCHI  | combatrefined               | 1.4.1           | combatrefined-1.4.2.jar                     | None                                     |
       | LCHI  | comforts                    | 1.4.1.2         | comforts-1.12.2-1.4.1.2.jar                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCHI  | concreteconversion          | 1.2.1           | Concrete+Conversion-1.12.2-1.2.1.jar        | None                                     |
       | LCHI  | concreteplus                | 1.1.2           | ConcreteExtends-1.1.2_1.12.jar              | None                                     |
       | LCHI  | consolehud                  | 1.4.1           | ConsoleHUD-v1.4.1-1.12.2.jar                | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHI  | craftablesaddles            | 1.3             | Craftable+Saddles[1.12]-1.3.jar             | None                                     |
       | LCHI  | dymm                        | 2.0.0           | DocumentYourModMod-2.0.0.jar                | None                                     |
       | LCHI  | orelib                      | 3.6.0.1         | OreLib-1.12.2-3.6.0.1.jar                   | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | dsurround                   | 3.6.0.2         | DynamicSurroundings-1.12.2-3.6.0.2.jar      | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHI  | dynamictrees                | 1.12.2-0.9.6    | DynamicTrees-1.12.2-0.9.6.jar               | None                                     |
       | LCHI  | easyflint                   | 1.1.0           | EasyFlint-1.12.2-1.1.0.jar                  | None                                     |
       | LCHI  | mod_lavacow                 | 1.0.12          | Fishs_Undead_Rising-1.0.12.jar              | None                                     |
       | LCHI  | fivefeetsmall               | 1.0.1           | FiveFeetSmall-v1.0.1-1.12.2.jar             | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHI  | gamblingstyle               | 1.0.1           | GamblingStyle-v1.0.1-1.12.2.jar             | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHI  | giacomosfoundry             | 1.3.13          | GiacomosFoundry-1.12.2-1.3.13.jar           | None                                     |
       | LCHI  | giacomos_maps               | 1.2.3           | GiacomosMaps-1.12.2-1.2.3.jar               | None                                     |
       | LCHI  | grapplemod                  | 1.12.2-v11.1    | grapplemod-v11.1-1.12.2.jar                 | None                                     |
       | LCHI  | guardillagers               | 1.0.1           | guardillagers-1.12.2-1.0.1.jar              | None                                     |
       | LCHI  | hatstands                   | 1.0.0           | hatstands-1.0.0-1.12.2.jar                  | None                                     |
       | LCHI  | homingexporbs               | 1.1             | HomingExpOrbs-1.1.jar                       | None                                     |
       | LCHI  | llibrary                    | 1.7.19          | llibrary-1.7.19-1.12.2.jar                  | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCHI  | iceandfire                  | 1.8.3           | iceandfire-1.8.3.jar                        | None                                     |
       | LCHI  | mantle                      | 1.12-1.3.3.55   | Mantle-1.12-1.3.3.55.jar                    | None                                     |
       | LCHI  | inspirations                | 1.12.2-0.2.9    | Inspirations-1.12.2-0.2.9.jar               | None                                     |
       | LCHI  | jaff                        | 1.7_for_1.12    | JustAFewFish-1.7_for_1.12.jar               | None                                     |
       | LCHI  | jeresources                 | 0.9.2.60        | JustEnoughResources-1.12.2-0.9.2.60.jar     | None                                     |
       | LCHI  | leatherworks                | 1.78.0          | LeatherWorks-1.12-1.78.0.42.jar             | None                                     |
       | LCHI  | libraryex                   | 1.0.12          | LibraryEx-1.12.2-1.0.12.jar                 | None                                     |
       | LCHI  | mage                        | 0.2.4           | MAGE-0.2.4.jar                              | None                                     |
       | LCHE  | mia                         | 1.12.2-0.1.0c   | mia-1.12.2-0.1.0c.jar                       | None                                     |
       | LCH   | mirageorb                   | 1.1.0           | mirageorb-1.12.2-1.1.0.jar                  | None                                     |
       | LCH   | mowziesmobs                 | 1.5.4           | mowziesmobs-1.5.4.jar                       | None                                     |
       | LCH   | multimob                    | 1.0.5           | multimob-1.0.5.jar                          | None                                     |
       | LCH   | mutantbeasts                | 0.6.1           | MutantBeasts-1.12.2-0.6.1.jar               | None                                     |
       | LCH   | naturalbabyanimals          | 1.2.0           | naturalbabyanimals-1.2.0-mc1.12.x.jar       | None                                     |
       | LCH   | netherex                    | 2.0.14          | NetherEx-1.12.2-2.0.14.jar                  | None                                     |
       | LCH   | rustic                      | 1.1.2           | rustic-1.1.2.jar                            | None                                     |
       | LCH   | ore_stone_variants          | 4.6             | ore_stone_variants-4.6.jar                  | None                                     |
       | LCH   | oregenmod                   | 1.0             | OreGenModMC1.12.2-1.5.1.jar                 | None                                     |
       | LCH   | paraglider                  | 1.0.1.5         | Paraglider-1.12.2-1.0.1.5.jar               | None                                     |
       | LCH   | paths                       | 1.0             | paths-1.6.1.jar                             | None                                     |
       | LCH   | potionofaiming              | 1.0.0           | potionofaiming-1.12.2-1.0.0.jar             | None                                     |
       | LCH   | powerdrop                   | MC1.12.2-1.1.2  | PowerDrop-MC1.12.2-1.1.2.jar                | None                                     |
       | LCH   | primitivemobs               | 1.2.3a          | primitivemobs-1.2.3a.jar                    | None                                     |
       | LCH   | quarkoddities               | 1               | QuarkOddities-1.12.2.jar                    | None                                     |
       | LCH   | reagenchant                 | 1.0.0           | Reagenchant-1.12.2-1.0.0.jar                | None                                     |
       | LCH   | realisticbrewingstand       | 3.1.0           | realisticbrewingstand-3.1.0.jar             | None                                     |
       | LCH   | respawnablepets             | 1.0.6           | respawnable-pets-1.0.6.1.jar                | None                                     |
       | LCH   | rbeacons                    | 1.0.0           | responsivebeacons-1.0.0-1.12.2.jar          | None                                     |
       | LCH   | savemystronghold            | 1.12.2-1.0.0    | savemystronghold-1.12.2-1.0.0.jar           | None                                     |
       | LCH   | sbirds                      | 1.12.2-1.0.0    | sbirds-1.12.2-1.1.0.jar                     | None                                     |
       | LCH   | shouldersurfing             | 1.16            | ShoulderSurfing-1.12.2-1.15.1.jar           | d6261bb645f41db84c74f98e512c2bb43f188af2 |
       | LCH   | simulatednights             | 1.12-2.1.0      | simulatednights-1.12-2.1.0.jar              | None                                     |
       | LCH   | smarthud                    | 2.0.2           | smarthud-2.0.2.jar                          | None                                     |
       | LCH   | smooth-scrolling-everywhere | 1.0             | smooth-scrolling-everywhere-1.0.jar         | None                                     |
       | LCH   | somelikeitdry               | 1.2.2           | somelikeitdry-1.2.2.jar                     | None                                     |
       | LCH   | soundphysics                | 1.0.8-1         | Sound-Physics-1.12.2.jar                    | None                                     |
       | LCH   | surge                       | 2.0.77          | Surge-1.12.2-2.0.77.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | tanspit                     | 1.12.2-1.3      | tanspit-1.12.2-1.4.jar                      | None                                     |
       | LCH   | vanillafix                  | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar                    | None                                     |
       | LCH   | veining                     | 1.3.2           | veining-1.3.2-1.12.x.jar                    | None                                     |
       | LCH   | villagenames                | 3.2.3           | VillageNames-1.12.2-3.2.3.jar               | None                                     |
       | LCH   | watercontrolextreme         | 1.0.0           | WaterControlExtreme-1.0.2.jar               | None                                     |
       | LCH   | wearablebackpacks           | 3.1.4           | WearableBackpacks-1.12.2-3.1.4.jar          | None                                     |
       | LCH   | wooltostring                | 1.12.2          | WoolToString-1.12.2-1.0.0.jar               | None                                     |
       | LCH   | xpfromharvest               | 1.1.0           | xpfromharvest-1.12.2-1.1.0.jar              | None                                     |
       | LCH   | zenny3d.saturationoverflow  | 1.1.1           | zenny3d.saturationoverflow-1.1.1.jar        | None                                     |
       | LCH   | phosphor-lighting           | 1.12.2-0.2.6    | phosphor-1.12.2-0.2.6+build50-universal.jar | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LCH   | snowrealmagic               | 0.3.3           | SnowRealMagic-0.3.3.jar                     | None                                     |
       | LCH   | worldsretold                | 1.0.7           | Worlds+Retold-+(v1.0.7)+14.23.5.2784.jar    | None                                     |
  Loaded coremods (and transformers): Quark Plugin (Quark-r1.6-177.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      iceandfire (iceandfire-1.8.3.jar)
                                        com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      ShoulderPlugin (ShoulderSurfing-1.12.2-1.15.1.jar)
                                        com.teamderpy.shouldersurfing.asm.ShoulderTransformations
                                      Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      MageCoremod (MAGE-0.2.4.jar)
                                        pl.asie.mage.core.EntityRendererTransformer
                                        pl.asie.mage.core.SmoothWaterTransformer
                                        pl.asie.mage.core.TextureAtlasSpriteTransformer
                                      TransformLoader (DynamicSurroundings-1.12.2-3.6.0.2.jar)
                                        
                                      ParagliderLoadingPlugin (Paraglider-1.12.2-1.0.1.5.jar)
                                        com.tictim.paraglider.asm.TransformerModelBiped
                                      ColytraLoadingPlugin (colytra-1.12.2-1.2.0.4.jar)
                                        c4.colytra.asm.ElytraTransformer
                                      CorePlugin (SmoothFont-mc1.12.2-2.1.1.jar)
                                        bre.smoothfont.asm.Transformer
                                      RandomPatches (randompatches-1.12.2-1.21.0.0.jar)
                                        com.therandomlabs.randompatches.core.RPTransformer
                                      llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Realistic Brewing Stand (realisticbrewingstand-3.1.0.jar)
                                        mjaroslav.mcmods.realisticbrewingstand.gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
                                      BetterFoliageLoader (BetterFoliage-MC1.12-2.3.1.jar)
                                        mods.betterfoliage.loader.BetterFoliageTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      ItemPatchingLoader (ItemPhysic+Lite+1.3.7+mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      CharmLoadingPlugin (Charm-1.12.2-1.3.6.jar)
                                        svenhjol.charm.base.CharmClassTransformer
                                      CoreModLoader (Sound-Physics-1.12.2.jar)
                                        com.sonicether.soundphysics.CoreModInjector
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 441.87' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
  Pulsar/inspirations loaded Pulses: - InspirationsShared (Enabled/Forced)
                                     - InspirationsBuilding (Enabled/Not Forced)
                                     - InspirationsUtility (Enabled/Not Forced)
                                     - InspirationsTools (Enabled/Not Forced)
                                     - InspirationsRecipes (Enabled/Not Forced)
                                     - InspirationsTweaks (Enabled/Not Forced)
                                     - InspirationsShared (Enabled/Forced)
                                     - ToughAsNailsPlugin (Enabled/Not Forced)
                                     - LeatherWorks (Enabled/Not Forced)
  Suspected Mods: Just Enough Resources (jeresources), Minor Integration and Additions (mia)
  Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

**Comment by SokyranTheDragon** [comment]
Hmm... It's an issue I haven't really expected to see. I'm not exactly sure what's causing it, as I've never seen it before, but my guess is that it might be related to some of the mods you're using.

One thing that I'm wondering about is, would the game load if you remove this mod? This looks like it might cause issue with JustEnoughResources as well.

Anyway, I'll start digging deeper into it, trying to find the cause for that.

**Comment by SokyranTheDragon** [comment]
Fixed, update should be up soon
