### ISSUE TITLE
Thermal Foundation causing crash without Tinkers Construct installed

### ISSUE THREAD

**Issue by BugmanBugman** [SokyranTheDragon/Minor-Integrations-and-Additions-MIA-#9]
https://paste.dimdev.org/axesipipax.mccrash

**Comment by SokyranTheDragon** [comment]
This is a dumb mistake on my part. It's something I did back when I just started working on this mod, and haven't really touched since then. I'm going to fix it and hopefully upload the fix within the next few hours, as I'm going to look at some other issues as well.
